version: '3'
services:
  user.api:
    build: ./user.api
    ports:
     - "8081:8080"
    volumes:
     - ./user.api/src:/var/codebase/src
    depends_on:
     - redis
  post.api:
    build: ./post.api
    ports:
     - "8082:8080"
    volumes:
     - ./post.api/src:/var/codebase/src
    depends_on:
     - redis
  redis:
    image: "redis:latest"
